version: "3.9"
services:

  db:
    image: mysql:latest
  # image: mariadb:latest # MariaDB
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: qmnmdit
      MYSQL_ROOT_PASSWORD: password

  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  wp:
    depends_on:
      - db
    links:
      - db
    image: wordpress:latest
    restart: always
    volumes:
      - ../wp/:/var/www/html
      - ../jps/:/var/www/html/wp-content/themes/jps # Jean-Paul Sartre (https://github.com/fedtti/jps#readme)
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: qmnmdit
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password

volumes:
  db_data:
