version: "3.9"
services:
  database:
    image: mysql:latest
  # image: mariadb:latest # MariaDB
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    depends_on:
      - database
    links:
      - database
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 3000:80
    restart: always
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  wordpress:
    depends_on:
      - database
    links:
      - database
    image: wordpress:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - ../wp/:/var/www/html
      - ../jps/:/var/www/html/wp-content/themes/jps # Jean-Paul Sartre (https://github.com/fedtti/jps#readme)
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}

# webserver:
  # depends_on:
    # - wordpress
  # image: ngnix:latest # NGINX
  # ports:
    # - 8080:80
  # restart: always
  # volumes:
    # - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db-data: {}
