version: "3.7"
services:

  db:
    image: mysql:latest
    volumes:
      - "db_data:/var/lib/mysql"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

  wp:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - "./wp/:/var/www/html"
      - "./jps/:/var/www/html/wp-content/themes/jps" # Jean-Paul Sartre (https://github.com/fedtti/jps)
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"

volumes:
  db_data:
